### ISSUE TITLE
Ctrlr panel for 003 synth

### ISSUE THREAD

**Issue by HLammers** [ChrisBall/003_Synth#1]
Hi Chris, this is the Ctrlr panel I built quickly to test the 003 synth.
[003 Ctrlr panel.zip](https://github.com/ChrisBall/003_Synth/files/7529479/003.Ctrlr.panel.zip)

**Comment by ChrisBall** [comment]
Thanks! I'll add it to the repo - if that's ok?

**Comment by ChrisBall** [comment]
I'm adding it! Let me know if there's a problem.
