### ISSUE TITLE
Missing Tape Delay ?

### ISSUE THREAD

**Issue by ragededent** [ChrisBall/003_Synth#2]
Hello,

Thanks for this great work. It is very clear code.

It seems that the TapeDelayEffect library is not included in your project (or maybe it is now included in teensyduino libraries and I couldn't manage to find it). So I changed a little bit to AudioDelayEffect in order to compile.

However I don't get any sound even after changing som control value (44 as you said). Any idea ? I run the 4.1 with SGTL5000.
(EDIT) Sorry, after trying playing a note directly from the code (inside CPU print loop), it does produce sound. It looks like it receives notes and ctrl fomr Live only on channel 3.... ?!

Thanks again for your work.

**Comment by ChrisBall** [comment]
Hi! 

The modified effect_delay.h and effect delay.cpp files that include the TapeDelayEffect object are here:

https://github.com/ChrisBall/003_Synth/tree/main/code/modified%20audio%20lib%20files

And yes, you're correct - currently it's only set up to receive hardware MIDI over serial3, but I think this is easily altered.

**Comment by ragededent** [comment]
Thanks !
